workspace = {members  =[ "ioddengine", "wasm","cli", "iotcoreconnect"]}

[package]
name = "ioddlib"
version = "0.1.0"
edition = "2021"


[lib]
name = "your_library_name"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.81"
